### ISSUE TITLE
Maintance intended?

### ISSUE THREAD

**Issue by cez-aug** [chrisenytc/node-doc#2]
Oi Christopher, último commit tem 3 anos. O projeto foi abandonado ou transferido para outro lugar? Algum plano pra ele?

**Comment by chrisenytc** [comment]
Oi Cezar. Infelizmente eu não tenho mais tempo para mantê-lo, mas caso tenha algum interesse em dar continuidade fique a vontade. A versão dessa doc do node.js é um pouco antiga e não me recordo se é compatível com a forma como é gerada a documentação atual do node. Mas é muito provável que seja ^_^

**Comment by cez-aug** [comment]
:+1:
